[ dependencies ]
alsa-utils # ALSA CLI control
playerctl  # Pulse audio CLI control
xbindkeys  # Figure out the XF86 names for keys
perf       # perf command
gpsd       # get lat,long coordinates

[ aur ]
flamegraph-git  # Tools to generate flamegraphs from perf(1)
